import { CommonModule, CurrencyPipe } from '@angular/common';
import { Component, OnInit, inject } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { Manutencao, ManutencaoRequest, Veiculo } from '../../core/models/api.models';
import { ManutencaoService } from '../../core/services/manutencao.service';
import { VeiculoService } from '../../core/services/veiculo.service';
import { cleanPayload, errorMessage, todayIso } from '../../shared/form-utils';
import { label, statusManutencaoOptions, tipoManutencaoOptions } from '../../shared/options';
@Component({ selector:'app-manutencoes', standalone:true, imports:[CommonModule,ReactiveFormsModule,CurrencyPipe], templateUrl:'./manutencoes.component.html' })
export class ManutencoesComponent implements OnInit { private fb=inject(FormBuilder); private service=inject(ManutencaoService); private veiculoService=inject(VeiculoService); itens:Manutencao[]=[]; veiculos:Veiculo[]=[]; editId?:number; mostrarForm=false; erro=''; sucesso=''; label=label; tipos=tipoManutencaoOptions; status=statusManutencaoOptions;
form=this.fb.group({veiculoId:[null as number|null,Validators.required],tipo:['TROCA_OLEO',Validators.required],status:[null as string|null],dataManutencao:[todayIso(),Validators.required],kmAtual:[null as number|null],descricao:['',Validators.required],oficina:[''],custoPecas:[0],custoMaoObra:[0],proximaManutencaoKm:[null as number|null],proximaManutencaoData:[null as string|null],observacao:['']}); ngOnInit(){this.carregar();this.veiculoService.listar().subscribe(r=>this.veiculos=r);} carregar(){this.service.listar().subscribe({next:r=>this.itens=r,error:e=>this.erro=errorMessage(e)});} novo(){this.editId=undefined;this.form.reset({tipo:'TROCA_OLEO',dataManutencao:todayIso(),custoPecas:0,custoMaoObra:0});this.mostrarForm=true;} editar(m:Manutencao){this.editId=m.id;this.form.reset({...m});this.mostrarForm=true;} salvar(){if(this.form.invalid){this.form.markAllAsTouched();return;} const p=cleanPayload(this.form.getRawValue()) as unknown as ManutencaoRequest; const req=this.editId?this.service.atualizar(this.editId,p):this.service.criar(p); req.subscribe({next:()=>{this.sucesso='Manutenção salva';this.mostrarForm=false;this.carregar();},error:e=>this.erro=errorMessage(e)});} iniciar(id:number){this.service.iniciar(id).subscribe({next:()=>this.carregar(),error:e=>this.erro=errorMessage(e)});} concluir(id:number){this.service.concluir(id).subscribe({next:()=>this.carregar(),error:e=>this.erro=errorMessage(e)});} cancelar(id:number){this.service.cancelar(id).subscribe({next:()=>this.carregar(),error:e=>this.erro=errorMessage(e)});} deletar(id:number){if(confirm('Excluir manutenção?'))this.service.deletar(id).subscribe({next:()=>this.carregar(),error:e=>this.erro=errorMessage(e)});} }
