import { CommonModule, CurrencyPipe } from '@angular/common';
import { Component, OnInit, inject } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { Abastecimento, AbastecimentoRequest, Motorista, Veiculo } from '../../core/models/api.models';
import { AbastecimentoService } from '../../core/services/abastecimento.service';
import { MotoristaService } from '../../core/services/motorista.service';
import { VeiculoService } from '../../core/services/veiculo.service';
import { cleanPayload, errorMessage, todayIso } from '../../shared/form-utils';
@Component({ selector:'app-abastecimentos', standalone:true, imports:[CommonModule,ReactiveFormsModule,CurrencyPipe], templateUrl:'./abastecimentos.component.html' })
export class AbastecimentosComponent implements OnInit { private fb=inject(FormBuilder); private service=inject(AbastecimentoService); private veiculoService=inject(VeiculoService); private motoristaService=inject(MotoristaService); itens:Abastecimento[]=[]; veiculos:Veiculo[]=[]; motoristas:Motorista[]=[]; erro=''; sucesso=''; mostrarForm=false;
form=this.fb.group({veiculoId:[null as number|null,Validators.required],motoristaId:[null as number|null],dataAbastecimento:[todayIso(),Validators.required],kmAtual:[0,Validators.required],litros:[0,Validators.required],valorLitro:[0,Validators.required],posto:[''],observacao:['']}); ngOnInit(){this.carregar();this.veiculoService.listar().subscribe(r=>this.veiculos=r);this.motoristaService.listar().subscribe(r=>this.motoristas=r);} carregar(){this.service.listar().subscribe({next:r=>this.itens=r,error:e=>this.erro=errorMessage(e)});} novo(){this.form.reset({dataAbastecimento:todayIso(),kmAtual:0,litros:0,valorLitro:0});this.mostrarForm=true;} salvar(){if(this.form.invalid){this.form.markAllAsTouched();return;} const p=cleanPayload(this.form.getRawValue()) as unknown as AbastecimentoRequest; this.service.criar(p).subscribe({next:()=>{this.sucesso='Abastecimento lançado e despesa gerada';this.mostrarForm=false;this.carregar();},error:e=>this.erro=errorMessage(e)});} deletar(id:number){if(confirm('Excluir abastecimento?'))this.service.deletar(id).subscribe({next:()=>this.carregar(),error:e=>this.erro=errorMessage(e)});} }
