import { CommonModule, CurrencyPipe } from '@angular/common';
import { Component, OnInit, inject } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { Cliente, Motorista, OrdemServico, OrdemServicoRequest, Veiculo } from '../../core/models/api.models';
import { ClienteService } from '../../core/services/cliente.service';
import { MotoristaService } from '../../core/services/motorista.service';
import { OrdemServicoService } from '../../core/services/ordem-servico.service';
import { VeiculoService } from '../../core/services/veiculo.service';
import { cleanPayload, errorMessage } from '../../shared/form-utils';
import { label, statusOrdemOptions, tipoServicoOptions } from '../../shared/options';
@Component({ selector:'app-ordens-servico', standalone:true, imports:[CommonModule,ReactiveFormsModule,CurrencyPipe], templateUrl:'./ordens-servico.component.html' })
export class OrdensServicoComponent implements OnInit { private fb=inject(FormBuilder); private service=inject(OrdemServicoService); private clienteService=inject(ClienteService); private veiculoService=inject(VeiculoService); private motoristaService=inject(MotoristaService); itens:OrdemServico[]=[]; clientes:Cliente[]=[]; veiculos:Veiculo[]=[]; motoristas:Motorista[]=[]; editId?:number; mostrarForm=false; erro=''; sucesso=''; label=label; tipoOptions=tipoServicoOptions; statusOptions=statusOrdemOptions;
form=this.fb.group({clienteId:[null as number|null,Validators.required],veiculoId:[null as number|null],motoristaId:[null as number|null],tipoServico:['REMOCAO_VEICULO_LEVE',Validators.required],status:[null as string|null],origem:['',Validators.required],destino:[''],kmEstimado:[null as number|null],kmReal:[null as number|null],valorCobrado:[0],custoEstimado:[0],observacao:['']});
ngOnInit(){this.carregar(); this.clienteService.listar().subscribe(r=>this.clientes=r); this.veiculoService.listar().subscribe(r=>this.veiculos=r); this.motoristaService.listar().subscribe(r=>this.motoristas=r);} carregar(){this.service.listar().subscribe({next:r=>this.itens=r,error:e=>this.erro=errorMessage(e)});} novo(){this.editId=undefined;this.form.reset({tipoServico:'REMOCAO_VEICULO_LEVE',valorCobrado:0,custoEstimado:0});this.mostrarForm=true;} editar(o:OrdemServico){this.editId=o.id;this.form.reset({...o});this.mostrarForm=true;} salvar(){if(this.form.invalid){this.form.markAllAsTouched();return;} const p=cleanPayload(this.form.getRawValue()) as unknown as OrdemServicoRequest; const req=this.editId?this.service.atualizar(this.editId,p):this.service.criar(p); req.subscribe({next:()=>{this.sucesso='Ordem salva com sucesso';this.mostrarForm=false;this.carregar();},error:e=>this.erro=errorMessage(e)});} deletar(id:number){if(confirm('Excluir OS?'))this.service.deletar(id).subscribe({next:()=>this.carregar(),error:e=>this.erro=errorMessage(e)});} iniciar(id:number){this.service.iniciar(id).subscribe({next:()=>this.carregar(),error:e=>this.erro=errorMessage(e)});} concluir(id:number){const km=prompt('KM real da conclusão:');this.service.concluir(id, km?Number(km):null).subscribe({next:()=>this.carregar(),error:e=>this.erro=errorMessage(e)});} faturar(id:number){this.service.faturar(id).subscribe({next:()=>this.carregar(),error:e=>this.erro=errorMessage(e)});} cancelar(id:number){this.service.cancelar(id).subscribe({next:()=>this.carregar(),error:e=>this.erro=errorMessage(e)});} }
