import { CommonModule, CurrencyPipe } from '@angular/common';
import { Component, OnInit, inject } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { DocumentoVeiculo, DocumentoVeiculoRequest, Veiculo } from '../../core/models/api.models';
import { DocumentoVeiculoService } from '../../core/services/documento-veiculo.service';
import { VeiculoService } from '../../core/services/veiculo.service';
import { cleanPayload, errorMessage, todayIso } from '../../shared/form-utils';
import { label, statusDocumentoOptions, tipoDocumentoOptions } from '../../shared/options';
@Component({ selector:'app-documentos-veiculos', standalone:true, imports:[CommonModule,ReactiveFormsModule,CurrencyPipe], templateUrl:'./documentos-veiculos.component.html' })
export class DocumentosVeiculosComponent implements OnInit { private fb=inject(FormBuilder); private service=inject(DocumentoVeiculoService); private veiculoService=inject(VeiculoService); itens:DocumentoVeiculo[]=[]; veiculos:Veiculo[]=[]; editId?:number; mostrarForm=false; erro=''; sucesso=''; label=label; tipos=tipoDocumentoOptions; status=statusDocumentoOptions;
form=this.fb.group({veiculoId:[null as number|null,Validators.required],tipo:['CRLV',Validators.required],status:[null as string|null],numeroDocumento:[''],dataEmissao:[todayIso()],dataVencimento:['',Validators.required],valor:[0],orgaoEmissor:[''],arquivoUrl:[''],observacao:['']}); ngOnInit(){this.carregar();this.veiculoService.listar().subscribe(r=>this.veiculos=r);} carregar(){this.service.listar().subscribe({next:r=>this.itens=r,error:e=>this.erro=errorMessage(e)});} novo(){this.editId=undefined;this.form.reset({tipo:'CRLV',dataEmissao:todayIso(),valor:0});this.mostrarForm=true;} editar(d:DocumentoVeiculo){this.editId=d.id;this.form.reset({...d});this.mostrarForm=true;} salvar(){if(this.form.invalid){this.form.markAllAsTouched();return;} const p=cleanPayload(this.form.getRawValue()) as unknown as DocumentoVeiculoRequest; const req=this.editId?this.service.atualizar(this.editId,p):this.service.criar(p); req.subscribe({next:()=>{this.sucesso='Documento salvo';this.mostrarForm=false;this.carregar();},error:e=>this.erro=errorMessage(e)});} atualizarStatus(id:number){this.service.atualizarStatus(id).subscribe({next:()=>this.carregar(),error:e=>this.erro=errorMessage(e)});} gerarDespesa(id:number){this.service.gerarDespesa(id).subscribe({next:()=>this.carregar(),error:e=>this.erro=errorMessage(e)});} cancelar(id:number){this.service.cancelar(id).subscribe({next:()=>this.carregar(),error:e=>this.erro=errorMessage(e)});} deletar(id:number){if(confirm('Excluir documento?'))this.service.deletar(id).subscribe({next:()=>this.carregar(),error:e=>this.erro=errorMessage(e)});} }
